name: shoppingCart/ReactJs
on:
  push:
    branches: [main]
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          ssh -t -t -i $SSH_KEY_PATH $SSH_USER@$SSH_SERVER_IP "cd ${PATH_TO_PROJECT};
          git reset --hard;
          rm -rf dist
          yarn install;
          yarn build;"

        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_SERVER_IP: ${{secrets.SSH_SERVER_IP}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
          SSH_USER: ${{ secrets.SSH_USER }}
          PATH_TO_PROJECT: ${{ secrets.PATH_TO_PROJECT }}
